// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbMIESk3_9ZOm_1lV4NDdQP2ti5ZRXH_0',
    appId: '1:750008653038:web:1ee3a99aa14f797e8e0fff',
    messagingSenderId: '750008653038',
    projectId: 'ukruzwa-59e53',
    authDomain: 'ukruzwa-59e53.firebaseapp.com',
    storageBucket: 'ukruzwa-59e53.appspot.com',
    measurementId: 'G-8SQ52W2PSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWutKPPQp_mPyNao755I0MwmcseSdRXpE',
    appId: '1:750008653038:android:480e504d133845538e0fff',
    messagingSenderId: '750008653038',
    projectId: 'ukruzwa-59e53',
    storageBucket: 'ukruzwa-59e53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqNXLN-_CwDeflTWqtsUo0K1Ggq5Mpa5M',
    appId: '1:750008653038:ios:3bedda868bd2ab748e0fff',
    messagingSenderId: '750008653038',
    projectId: 'ukruzwa-59e53',
    storageBucket: 'ukruzwa-59e53.appspot.com',
    iosBundleId: 'com.example.ukruzwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqNXLN-_CwDeflTWqtsUo0K1Ggq5Mpa5M',
    appId: '1:750008653038:ios:3bedda868bd2ab748e0fff',
    messagingSenderId: '750008653038',
    projectId: 'ukruzwa-59e53',
    storageBucket: 'ukruzwa-59e53.appspot.com',
    iosBundleId: 'com.example.ukruzwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbMIESk3_9ZOm_1lV4NDdQP2ti5ZRXH_0',
    appId: '1:750008653038:web:2adc19360c2a861f8e0fff',
    messagingSenderId: '750008653038',
    projectId: 'ukruzwa-59e53',
    authDomain: 'ukruzwa-59e53.firebaseapp.com',
    storageBucket: 'ukruzwa-59e53.appspot.com',
    measurementId: 'G-BKCW2F60M8',
  );
}
